const oracledb = require('oracledb');
const dotenv = require('dotenv');

dotenv.config();

let pool = null;

async function initPool() {
    try {
        pool = await oracledb.createPool({
            user: process.env.DB_USER || 'technest_user',
            password: process.env.DB_PASSWORD || 'TechNest@123',
            connectString: process.env.DB_CONNECTION_STRING || 'localhost:1521/xe',
            poolMin: 2,
            poolMax: 10,
            poolIncrement: 1
        });

        console.log('✓ Oracle Database Pool Created');
        await createTables();
    } catch (err) {
        console.error('✗ Database Pool Error:', err.message);
        process.exit(1);
    }
}

async function createTables() {
    let conn;
    try {
        conn = await pool.getConnection();

        // Users Table
        await conn.execute(`
            CREATE TABLE IF NOT EXISTS users (
                user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR2(50) UNIQUE NOT NULL,
                email VARCHAR2(100) UNIQUE NOT NULL,
                password VARCHAR2(255) NOT NULL,
                first_name VARCHAR2(50),
                last_name VARCHAR2(50),
                phone VARCHAR2(20),
                address VARCHAR2(255),
                city VARCHAR2(50),
                state VARCHAR2(50),
                postal_code VARCHAR2(20),
                country VARCHAR2(50),
                is_active NUMBER(1) DEFAULT 1,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        `);

        // Sessions Table
        await conn.execute(`
            CREATE TABLE IF NOT EXISTS user_sessions (
                session_id VARCHAR2(255) PRIMARY KEY,
                user_id NUMBER NOT NULL,
                ip_address VARCHAR2(45),
                user_agent VARCHAR2(500),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                expires_at TIMESTAMP NOT NULL,
                is_active NUMBER(1) DEFAULT 1,
                FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
            )
        `);

        // Activity Logs Table
        await conn.execute(`
            CREATE TABLE IF NOT EXISTS activity_logs (
                log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id NUMBER NOT NULL,
                action VARCHAR2(100),
                ip_address VARCHAR2(45),
                details VARCHAR2(500),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
            )
        `);

        console.log('✓ Database Tables Verified/Created');
    } catch (err) {
        if (err.message.includes('already exists') || err.message.includes('ORA-00955')) {
            console.log('✓ Tables already exist');
        } else {
            console.error('✗ Table Creation Error:', err.message);
        }
    } finally {
        if (conn) {
            try { await conn.close(); } catch (err) {}
        }
    }
}

async function getConnection() {
    if (!pool) await initPool();
    return await pool.getConnection();
}

async function executeQuery(sql, params = [], options = {}) {
    let conn;
    try {
        conn = await getConnection();
        const result = await conn.execute(sql, params, options);
        return result;
    } catch (err) {
        console.error('DB Error:', err.message);
        throw err;
    } finally {
        if (conn) {
            try { await conn.close(); } catch (err) {}
        }
    }
}

async function closePool() {
    try {
        if (pool) {
            await pool.close(0);
            console.log('✓ Connection pool closed');
        }
    } catch (err) {
        console.error('Error closing pool:', err);
    }
}

process.on('SIGINT', async () => {
    console.log('\nShutting down...');
    await closePool();
    process.exit(0);
});

module.exports = {
    initPool,
    getConnection,
    executeQuery,
    closePool
};
